language: generic

sudo: false

addons:
  apt:
    packages:
    - ocaml-nox
    - coq

env:
  global:
  - INSTALL_DIR: $HOME/.local
  - ISABELLE_VERSION: Isabelle2016
  - ISABELLE_TARBALL: ${ISABELLE_VERSION}_app.tar.gz
  - ISABELLE_URL: http://isabelle.in.tum.de/dist/${ISABELLE_TARBALL}
  - ISABELLE_DIR: ${INSTALL_DIR}/${ISABELLE_VERSION}
  - ISABELLE: ${ISABELLE_DIR}/bin/isabelle
  - ISABELLE_USER_SETTINGS: ${HOME}/.isabelle/${ISABELLE_VERSION}/etc/settings
  - AFP_BRANCH: afp-2016
  - AFP_REPO: https://bitbucket.org/isa-afp/${AFP_BRANCH}
  - AFP_DIR: ${INSTALL_DIR}/${AFP_BRANCH}

cache:
  directories:
  - ${INSTALL_DIR}
  - $HOME/.isabelle

install:
  - mkdir -p ${INSTALL_DIR}
  - test -e $ISABELLE || { wget ${ISABELLE_URL} && tar -C ${INSTALL_DIR}/ -xzf ${ISABELLE_TARBALL}; }
  - test -d `$ISABELLE getenv -b ISABELLE_HOME_USER`/etc || mkdir -p `$ISABELLE getenv -b ISABELLE_HOME_USER`/etc
  - test -e `$ISABELLE getenv -b ISABELLE_HOME_USER`/etc/settings || echo 'export ML_OPTIONS="-H 500"' > `$ISABELLE getenv -b ISABELLE_HOME_USER`/etc/settings
  - test -e `$ISABELLE getenv -b ISABELLE_HOME`/heaps/`$ISABELLE getenv -b ML_IDENTIFIER`/HOL || $ISABELLE build -b -s -v -j 1 -o threads=1 HOL
  - test -e ${AFP_DIR} || (cd ${INSTALL_DIR}; hg clone ${AFP_REPO})
  - test -e ${ISABELLE_USER_SETTINGS} || { mkdir -p $(dirname ${ISABELLE_USER_SETTINGS}) && echo 'init_component "${AFP_DIR}"' > ${ISABELLE_USER_SETTINGS}; }
  - (cd ${AFP_DIR}; hg pull -u)

script: make ccomp
