language: generic

sudo: false

addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - ocaml

env:
  global:
  - INSTALL_DIR: $HOME/.local
  - ISABELLE_VERSION: Isabelle2016
  - ISABELLE_TARBALL: ${ISABELLE_VERSION}_app.tar.gz
  - ISABELLE_URL: http://isabelle.in.tum.de/dist/${ISABELLE_TARBALL}
  - ISABELLE_DIR: ${INSTALL_DIR}/${ISABELLE_VERSION}
  - ISABELLE: ${ISABELLE_DIR}/bin/isabelle
  - ISABELLE_USER_SETTINGS: ${HOME}/.isabelle/${ISABELLE_VERSION}/etc/settings
  - AFP_BRANCH: afp-2016
  - AFP_REPO: https://bitbucket.org/isa-afp/${AFP_BRANCH}
  - AFP_DIR: ${INSTALL_DIR}/${AFP_BRANCH}

cache:
  directories:
  - ${INSTALL_DIR}
  - ${HOME}/.isabelle

install:
  - test -d ${INSTALL_DIR} || mkdir -p ${INSTALL_DIR}
  - test -e $ISABELLE || { wget ${ISABELLE_URL} && tar -C ${INSTALL_DIR}/ -xzf ${ISABELLE_TARBALL}; }
  - test -e ${ISABELLE_USER_SETTINGS} || { mkdir -p $(dirname ${ISABELLE_USER_SETTINGS}) && echo 'init_component "${AFP_DIR}"' > ${ISABELLE_USER_SETTINGS}; }
  - grep ISABELLE_BUILD_OPTIONS ${ISABELLE_USER_SETTINGS} || echo 'ISABELLE_BUILD_OPTIONS="threads=1"' >> ${ISABELLE_USER_SETTINGS}
  - grep ML_OPTIONS ${ISABELLE_USER_SETTINGS} || echo 'ML_OPTIONS="-H 500"' >> ${ISABELLE_USER_SETTINGS}
  - test -e `$ISABELLE getenv -b ISABELLE_HOME`/heaps/`$ISABELLE getenv -b ML_IDENTIFIER`/HOL || $ISABELLE build -b -s -v HOL
  - test -d ${AFP_DIR} || (cd ${INSTALL_DIR}; hg clone ${AFP_REPO})
  - (cd ${AFP_DIR}; hg pull -u)

script: true || make FormalSSA ISABELLE=${ISABELLE}
